import { mysql, pgsql, tsql } from "@simplysm/core-common";
import type { ExpectedSql } from "../setup/test-utils";

export const singlePrimaryKey: ExpectedSql = {
  mysql: mysql`
    CREATE TABLE \`TestDb\`.\`User\` (
      \`id\` BIGINT NOT NULL,
      CONSTRAINT \`PK_User\` PRIMARY KEY (\`id\`)
    )
  `,
  mssql: tsql`
    CREATE TABLE [TestDb].[TestSchema].[User] (
      [id] BIGINT NOT NULL,
      CONSTRAINT [PK_User] PRIMARY KEY ([id])
    )
  `,
  postgresql: pgsql`
    CREATE TABLE "TestSchema"."User" (
      "id" BIGINT NOT NULL,
      CONSTRAINT "PK_User" PRIMARY KEY ("id")
    )
  `,
};

export const compositePrimaryKey: ExpectedSql = {
  mysql: mysql`
    CREATE TABLE \`TestDb\`.\`Order\` (
      \`userId\` BIGINT NOT NULL,
      \`productId\` BIGINT NOT NULL,
      \`quantity\` INT NOT NULL,
      CONSTRAINT \`PK_Order\` PRIMARY KEY (\`userId\`, \`productId\`)
    )
  `,
  mssql: tsql`
    CREATE TABLE [TestDb].[TestSchema].[Order] (
      [userId] BIGINT NOT NULL,
      [productId] BIGINT NOT NULL,
      [quantity] INT NOT NULL,
      CONSTRAINT [PK_Order] PRIMARY KEY ([userId], [productId])
    )
  `,
  postgresql: pgsql`
    CREATE TABLE "TestSchema"."Order" (
      "userId" BIGINT NOT NULL,
      "productId" BIGINT NOT NULL,
      "quantity" INTEGER NOT NULL,
      CONSTRAINT "PK_Order" PRIMARY KEY ("userId", "productId")
    )
  `,
};

export const complexOptions1: ExpectedSql = {
  mysql: mysql`
    CREATE TABLE \`TestDb\`.\`User\` (
      \`id\` BIGINT NOT NULL,
      \`name\` VARCHAR(100) NOT NULL,
      CONSTRAINT \`PK_User\` PRIMARY KEY (\`id\`)
    )
  `,
  mssql: tsql`
    CREATE TABLE [TestDb].[TestSchema].[User] (
      [id] BIGINT NOT NULL,
      [name] NVARCHAR(100) NOT NULL,
      CONSTRAINT [PK_User] PRIMARY KEY ([id])
    )
  `,
  postgresql: pgsql`
    CREATE TABLE "TestSchema"."User" (
      "id" BIGINT NOT NULL,
      "name" VARCHAR(100) NOT NULL,
      CONSTRAINT "PK_User" PRIMARY KEY ("id")
    )
  `,
};

export const complexOptions3: ExpectedSql = {
  mysql: mysql`
    CREATE TABLE \`TestDb\`.\`Product\` (
      \`id\` BIGINT NOT NULL AUTO_INCREMENT,
      \`name\` VARCHAR(200) NOT NULL,
      \`price\` DECIMAL(10, 2) NOT NULL,
      \`stock\` INT NOT NULL DEFAULT 0,
      \`isActive\` BOOLEAN NOT NULL DEFAULT TRUE,
      \`description\` LONGTEXT NULL,
      \`createdAt\` DATETIME NOT NULL,
      CONSTRAINT \`PK_Product\` PRIMARY KEY (\`id\`)
    )
  `,
  mssql: tsql`
    CREATE TABLE [TestDb].[TestSchema].[Product] (
      [id] BIGINT NOT NULL IDENTITY(1, 1),
      [name] NVARCHAR(200) NOT NULL,
      [price] DECIMAL(10, 2) NOT NULL,
      [stock] INT NOT NULL DEFAULT 0,
      [isActive] BIT NOT NULL DEFAULT 1,
      [description] NVARCHAR(MAX) NULL,
      [createdAt] DATETIME2 NOT NULL,
      CONSTRAINT [PK_Product] PRIMARY KEY ([id])
    )
  `,
  postgresql: pgsql`
    CREATE TABLE "TestSchema"."Product" (
      "id" BIGINT NOT NULL GENERATED BY DEFAULT AS IDENTITY,
      "name" VARCHAR(200) NOT NULL,
      "price" NUMERIC(10, 2) NOT NULL,
      "stock" INTEGER NOT NULL DEFAULT 0,
      "isActive" BOOLEAN NOT NULL DEFAULT TRUE,
      "description" TEXT NULL,
      "createdAt" TIMESTAMP NOT NULL,
      CONSTRAINT "PK_Product" PRIMARY KEY ("id")
    )
  `,
};
