packages:
  - packages/*
  - tests/*

ignoredBuiltDependencies:
  - core-js

onlyBuiltDependencies:
  - "@simplysm/claude"
  - bufferutil
  - cpu-features
  - esbuild
  - sharp
  - ssh2
  - utf-8-validate
