printWidth: 100
tabWidth: 2
useTabs: false
semi: true
quoteProps: consistent
trailingComma: all
bracketSpacing: true
bracketSameLine: false
arrowParens: always
endOfLine: lf
htmlWhitespaceSensitivity: ignore
embeddedLanguageFormatting: auto
