packages:
  - packages/*
  - tests/*

onlyBuiltDependencies:
  - "@simplysm/sd-claude"
  - bcrypt
  - bufferutil
  - core-js
  - cpu-features
  - esbuild
  - sharp
  - ssh2
  - unrs-resolver
  - utf-8-validate
