import type {
  AddColumnQueryDef,
  AddForeignKeyQueryDef,
  AddIndexQueryDef,
  AddPrimaryKeyQueryDef,
  ClearSchemaQueryDef,
  CreateProcQueryDef,
  CreateTableQueryDef,
  CreateViewQueryDef,
  SchemaExistsQueryDef,
  DeleteQueryDef,
  DropColumnQueryDef,
  DropForeignKeyQueryDef,
  DropIndexQueryDef,
  DropPrimaryKeyQueryDef,
  DropProcQueryDef,
  DropTableQueryDef,
  DropViewQueryDef,
  ExecProcQueryDef,
  InsertIfNotExistsQueryDef,
  InsertIntoQueryDef,
  InsertQueryDef,
  ModifyColumnQueryDef,
  QueryDefObjectName,
  RenameColumnQueryDef,
  RenameTableQueryDef,
  SelectQueryDef,
  SelectQueryDefJoin,
  SwitchFkQueryDef,
  TruncateQueryDef,
  UpdateQueryDef,
  UpsertQueryDef,
} from "../../types/query-def";
import type { WhereExpr } from "../../types/expr";
import type { QueryBuildResult } from "../../types/db";
import { QueryBuilderBase } from "../base/query-builder-base";
import { PostgresqlExprRenderer } from "./postgresql-expr-renderer";

/**
 * PostgreSQL QueryBuilder
 *
 * PostgreSQL 고유 사항:
 * - OUTPUT: RETURNING 절 사용 (네이티브 지원)
 * - TRUNCATE: RESTART IDENTITY 옵션 필요
 * - UPSERT: CTE 방식 (INSERT ... ON CONFLICT는 단일 유니크 제약조건만 지원)
 * - AUTO_INCREMENT: GENERATED BY DEFAULT AS IDENTITY (명시적 값 할당 가능)
 * - FK 추가 시 별도 인덱스 생성 필요 (MySQL과 다름)
 */
export class PostgresqlQueryBuilder extends QueryBuilderBase {
  protected expr = new PostgresqlExprRenderer((def) => this.select(def).sql);

  //#region ========== Utilities ==========

  /** 테이블명 렌더링 (PostgreSQL: database는 연결에서 처리, schema.table만 사용) */
  protected tableName(obj: QueryDefObjectName): string {
    const schema = obj.schema ?? "public";
    return `${this.expr.wrap(schema)}.${this.expr.wrap(obj.name)}`;
  }

  /** LIMIT...OFFSET 절 렌더링 */
  protected renderLimit(limit: [number, number] | undefined, top: number | undefined): string {
    if (limit != null) {
      const [offset, count] = limit;
      return ` LIMIT ${count} OFFSET ${offset}`;
    }
    if (top != null) {
      return ` LIMIT ${top}`;
    }
    return "";
  }

  protected renderJoin(join: SelectQueryDefJoin): string {
    const alias = this.expr.wrap(join.as);

    // LATERAL JOIN이 필요한지 감지
    if (this.needsLateral(join)) {
      // from이 배열(UNION ALL)이면 renderFrom(join.from) 사용,
      // 그 외(orderBy, top, select 등)이면 renderFrom(join)으로 서브쿼리 생성
      const from = Array.isArray(join.from) ? this.renderFrom(join.from) : this.renderFrom(join);
      return ` LEFT OUTER JOIN LATERAL ${from} AS ${alias} ON TRUE`;
    }

    // 일반 JOIN
    const from = this.renderFrom(join.from);
    if (this.isRecursiveSelfJoin(join)) {
      return ` CROSS JOIN ${from} AS ${alias}`;
    }
    const where =
      join.where != null && join.where.length > 0
        ? ` ON ${this.expr.renderWhere(join.where)}`
        : " ON TRUE";
    return ` LEFT OUTER JOIN ${from} AS ${alias}${where}`;
  }

  //#endregion

  //#region ========== DML - SELECT ==========

  protected select(def: SelectQueryDef): QueryBuildResult {
    // WITH (CTE)
    let sql = "";
    if (def.with != null) {
      const { name, base, recursive } = def.with;
      sql += `WITH RECURSIVE ${this.expr.wrap(name)} AS (${this.select(base).sql} UNION ALL ${this.select(recursive).sql}) `;
    }

    // SELECT
    sql += "SELECT";
    if (def.distinct) {
      sql += " DISTINCT";
    }

    // columns
    if (def.select != null) {
      const cols = Object.entries(def.select).map(
        ([alias, expr]) => `${this.expr.render(expr)} AS ${this.expr.wrap(alias)}`,
      );
      sql += ` ${cols.join(", ")}`;
    } else {
      sql += " *";
    }

    // FROM
    if (def.from != null) {
      const from = this.renderFrom(def.from);
      sql += ` FROM ${from} AS ${this.expr.wrap(def.as)}`;
    }

    // JOINs
    sql += this.renderJoins(def.joins);

    // WHERE
    sql += this.renderWhere(def.where);

    // GROUP BY
    sql += this.renderGroupBy(def.groupBy);

    // HAVING
    sql += this.renderHaving(def.having);

    // ORDER BY
    sql += this.renderOrderBy(def.orderBy);

    // LIMIT
    sql += this.renderLimit(def.limit, def.top);

    // LOCK (끝에 FOR UPDATE 추가)
    if (def.lock) {
      sql += " FOR UPDATE";
    }

    return { sql };
  }

  //#endregion

  //#region ========== DML - INSERT ==========

  protected insert(def: InsertQueryDef): QueryBuildResult {
    const table = this.tableName(def.table);

    if (def.records.length === 0) {
      throw new Error("INSERT에는 최소 1개의 레코드가 필요합니다.");
    }

    const columns = Object.keys(def.records[0]);
    const colList = columns.map((c) => this.expr.wrap(c)).join(", ");

    const valuesList = def.records.map((record) => {
      const values = columns.map((c) => this.expr.escapeValue(record[c]));
      return `(${values.join(", ")})`;
    });

    const insertCore = `INSERT INTO ${table} (${colList}) VALUES ${valuesList.join(", ")}`;

    // GENERATED BY DEFAULT AS IDENTITY는 명시적 값 삽입을 허용하지만, MSSQL/MySQL과 달리
    // 명시값을 넣어도 내부 시퀀스가 자동으로 전진하지 않는다. 보정하지 않으면 이후 값 없이
    // INSERT 시 이미 사용된 PK 값이 재발급되어 중복 오류가 발생한다.
    // → overrideIdentity인 경우 INSERT 후 setval로 시퀀스를 max 값으로 보정한다.
    const needSeqReset = def.overrideIdentity === true && def.aiColName != null;
    const aiColWrapped = def.aiColName != null ? this.expr.wrap(def.aiColName) : "";
    const seqExpr =
      def.aiColName != null
        ? `pg_get_serial_sequence(${this.expr.escapeValue(table)}, ${this.expr.escapeValue(def.aiColName)})`
        : "";

    if (def.output != null) {
      const outputCols = def.output.columns.map((c) => this.expr.wrap(c)).join(", ");

      if (!needSeqReset) {
        return { sql: `${insertCore} RETURNING ${outputCols}` };
      }

      // RETURNING + 시퀀스 보정: node-postgres는 multi-statement에서 마지막 결과만 반환하므로
      // INSERT를 data-modifying CTE로 감싸 RETURNING 결과를 보존하고, setval CTE를 메인 쿼리에서
      // 참조(CROSS JOIN)하여 반드시 실행되도록 한다. 보정 max는 기존 데이터와 새로 삽입된 행을
      // 모두 고려(GREATEST)한다. 단, 새 행은 INSERT CTE 효과가 보이지 않으므로 _ins에서 직접 조회.
      const returningCols = def.output.columns.includes(def.aiColName!)
        ? outputCols
        : `${outputCols}, ${aiColWrapped}`;
      const maxExpr = `GREATEST(COALESCE((SELECT MAX(${aiColWrapped}) FROM ${table}), 0), COALESCE((SELECT MAX(${aiColWrapped}) FROM "_ins"), 0))`;
      let sql = `WITH "_ins" AS (${insertCore} RETURNING ${returningCols}), `;
      sql += `"_seq" AS (SELECT setval(${seqExpr}, ${maxExpr}) AS "_v") `;
      sql += `SELECT ${outputCols} FROM "_ins", "_seq"`;
      return { sql };
    }

    if (!needSeqReset) {
      return { sql: insertCore };
    }

    // output이 없으면 결과를 사용하지 않으므로 INSERT 후 별도 statement로 시퀀스를 보정한다.
    // (별도 statement이므로 MAX는 방금 삽입된 행까지 반영된다)
    let sql = `${insertCore};\n`;
    sql += `SELECT setval(${seqExpr}, (SELECT MAX(${aiColWrapped}) FROM ${table}))`;
    return { sql };
  }

  protected insertIfNotExists(def: InsertIfNotExistsQueryDef): QueryBuildResult {
    const table = this.tableName(def.table);

    const columns = Object.keys(def.record);
    const colList = columns.map((c) => this.expr.wrap(c)).join(", ");
    const values = columns.map((c) => this.expr.escapeValue(def.record[c])).join(", ");

    // existsSelectQuery를 SELECT 1 AS _로 렌더링
    const existsQuerySql = this.select({
      ...def.existsSelectQuery,
      select: { _: { type: "value", value: 1 } },
    }).sql;

    let sql = `INSERT INTO ${table} (${colList}) SELECT ${values} WHERE NOT EXISTS (${existsQuerySql})`;

    // RETURNING 절
    if (def.output != null) {
      const outputCols = def.output.columns.map((c) => this.expr.wrap(c)).join(", ");
      sql += ` RETURNING ${outputCols}`;
    }

    return { sql };
  }

  protected insertInto(def: InsertIntoQueryDef): QueryBuildResult {
    const table = this.tableName(def.table);
    const selectSql = this.select(def.recordsSelectQuery).sql;

    // INSERT INTO SELECT에서 column 추출
    const selectDef = def.recordsSelectQuery;
    const colList =
      selectDef.select != null
        ? Object.keys(selectDef.select)
            .map((c) => this.expr.wrap(c))
            .join(", ")
        : "*";

    let sql = `INSERT INTO ${table} (${colList}) ${selectSql}`;

    // RETURNING 절
    if (def.output != null) {
      const outputCols = def.output.columns.map((c) => this.expr.wrap(c)).join(", ");
      sql += ` RETURNING ${outputCols}`;
    }

    return { sql };
  }

  //#endregion

  //#region ========== DML - UPDATE ==========

  protected update(def: UpdateQueryDef): QueryBuildResult {
    const table = this.tableName(def.table);
    const alias = this.expr.wrap(def.as);
    const hasLimit = def.top != null || def.limit != null;

    // SET
    const setParts = Object.entries(def.record).map(
      ([col, e]) => `${this.expr.wrap(col)} = ${this.expr.render(e)}`,
    );

    // CTE: top/limit → ctid 기반 서브쿼리
    let ctePart = "";
    if (hasLimit) {
      ctePart = this._buildLimitCte(def, table, alias);
    }

    let sql = `${ctePart}UPDATE ${table} AS ${alias} SET ${setParts.join(", ")}`;

    // PostgreSQL: JOIN은 FROM 절로 처리
    if (def.joins != null && def.joins.length > 0) {
      const joinTables = def.joins.map((j) => {
        const from = this.renderFrom(j.from);
        return `${from} AS ${this.expr.wrap(j.as)}`;
      });
      sql += ` FROM ${joinTables.join(", ")}`;

      const joinConditions = def.joins
        .filter((j) => j.where != null && j.where.length > 0)
        .map((j) => this.expr.renderWhere(j.where!));

      if (hasLimit) {
        // CTE가 WHERE 조건을 포함하므로 ctid 필터 + JOIN 조건만
        const conditions = [`${alias}.ctid IN (SELECT ctid FROM _limited)`, ...joinConditions];
        sql += ` WHERE ${conditions.join(" AND ")}`;
      } else {
        const whereCondition =
          def.where != null && def.where.length > 0 ? this.expr.renderWhere(def.where) : null;
        const allConditions =
          whereCondition != null ? [whereCondition, ...joinConditions] : joinConditions;
        if (allConditions.length > 0) {
          sql += ` WHERE ${allConditions.join(" AND ")}`;
        }
      }
    } else {
      if (hasLimit) {
        sql += ` WHERE ${alias}.ctid IN (SELECT ctid FROM _limited)`;
      } else {
        sql += this.renderWhere(def.where);
      }
    }

    // RETURNING 절
    if (def.output != null) {
      const outputCols = def.output.columns.map((c) => `${alias}.${this.expr.wrap(c)}`).join(", ");
      sql += ` RETURNING ${outputCols}`;
    }

    return { sql };
  }

  //#endregion

  //#region ========== DML - DELETE ==========

  protected delete(def: DeleteQueryDef): QueryBuildResult {
    const table = this.tableName(def.table);
    const alias = this.expr.wrap(def.as);
    const hasLimit = def.top != null || def.limit != null;

    // CTE: top/limit → ctid 기반 서브쿼리
    let ctePart = "";
    if (hasLimit) {
      ctePart = this._buildLimitCte(def, table, alias);
    }

    let sql = `${ctePart}DELETE FROM ${table} AS ${alias}`;

    // PostgreSQL: JOIN은 USING 절로 처리
    if (def.joins != null && def.joins.length > 0) {
      const joinTables = def.joins.map((j) => {
        const from = this.renderFrom(j.from);
        return `${from} AS ${this.expr.wrap(j.as)}`;
      });
      sql += ` USING ${joinTables.join(", ")}`;

      const joinConditions = def.joins
        .filter((j) => j.where != null && j.where.length > 0)
        .map((j) => this.expr.renderWhere(j.where!));

      if (hasLimit) {
        const conditions = [`${alias}.ctid IN (SELECT ctid FROM _limited)`, ...joinConditions];
        sql += ` WHERE ${conditions.join(" AND ")}`;
      } else {
        const whereCondition =
          def.where != null && def.where.length > 0 ? this.expr.renderWhere(def.where) : null;
        const allConditions =
          whereCondition != null ? [whereCondition, ...joinConditions] : joinConditions;
        if (allConditions.length > 0) {
          sql += ` WHERE ${allConditions.join(" AND ")}`;
        }
      }
    } else {
      if (hasLimit) {
        sql += ` WHERE ${alias}.ctid IN (SELECT ctid FROM _limited)`;
      } else {
        sql += this.renderWhere(def.where);
      }
    }

    // RETURNING (PostgreSQL: DELETE에서도 지원)
    if (def.output != null) {
      const outputCols = def.output.columns.map((c) => this.expr.wrap(c)).join(", ");
      sql += ` RETURNING ${outputCols}`;
    }

    return { sql };
  }

  //#endregion

  //#region ========== DML - UPSERT ==========

  protected upsert(def: UpsertQueryDef): QueryBuildResult {
    // PostgreSQL: CTE 방식 (ON CONFLICT는 단일 유니크 제약조건만 지원하므로 범용성을 위해 CTE 사용)
    const table = this.tableName(def.table);
    const alias = this.expr.wrap(def.existsSelectQuery.as);

    // UPDATE SET 부분
    const updateSetParts = Object.entries(def.updateRecord).map(
      ([col, e]) => `${this.expr.wrap(col)} = ${this.expr.render(e)}`,
    );

    // INSERT 부분
    const insertColumns = Object.keys(def.insertRecord);
    const insertColList = insertColumns.map((c) => this.expr.wrap(c)).join(", ");
    const insertValues = insertColumns.map((c) => this.expr.render(def.insertRecord[c])).join(", ");

    // WHERE 조건
    const whereCondition =
      def.existsSelectQuery.where != null && def.existsSelectQuery.where.length > 0
        ? this.expr.renderWhere(def.existsSelectQuery.where)
        : "TRUE";

    // OUTPUT column 정의
    const outputCols =
      def.output != null ? def.output.columns.map((c) => this.expr.wrap(c)).join(", ") : "*";

    // CTE 기반 UPSERT
    let sql = `WITH matched AS (\n`;
    sql += `  SELECT ${alias}.* FROM ${table} AS ${alias} WHERE ${whereCondition}\n`;
    sql += `),\n`;
    sql += `updated AS (\n`;
    sql += `  UPDATE ${table} AS ${alias} SET ${updateSetParts.join(", ")}\n`;
    sql += `  WHERE ${whereCondition}\n`;
    sql += `  RETURNING ${outputCols}\n`;
    sql += `),\n`;
    sql += `inserted AS (\n`;
    sql += `  INSERT INTO ${table} (${insertColList})\n`;
    sql += `  SELECT ${insertValues}\n`;
    sql += `  WHERE NOT EXISTS (SELECT 1 FROM matched)\n`;
    sql += `  RETURNING ${outputCols}\n`;
    sql += `)\n`;
    sql += `SELECT * FROM updated UNION ALL SELECT * FROM inserted`;

    return { sql };
  }

  //#endregion

  //#region ========== DDL - Table ==========

  protected createTable(def: CreateTableQueryDef): QueryBuildResult {
    const table = this.tableName(def.table);

    const colDefs = def.columns.map((col) => {
      let colSql = `${this.expr.wrap(col.name)} ${this.expr.renderDataType(col.dataType)}`;

      // nullable: true → NULL, 아니면 → NOT NULL
      if (col.nullable === true) {
        colSql += " NULL";
      } else {
        colSql += " NOT NULL";
      }

      if (col.autoIncrement) {
        colSql += " GENERATED BY DEFAULT AS IDENTITY";
      }

      if (col.default != null) {
        colSql += ` DEFAULT ${this.expr.escapeValue(col.default)}`;
      }

      return colSql;
    });

    // CONSTRAINT 이름이 포함된 Primary Key
    if (def.primaryKey != null && def.primaryKey.length > 0) {
      const pkCols = def.primaryKey.map((c) => this.expr.wrap(c)).join(", ");
      const pkName = this.expr.wrap(`PK_${def.table.name}`);
      colDefs.push(`CONSTRAINT ${pkName} PRIMARY KEY (${pkCols})`);
    }

    return { sql: `CREATE TABLE ${table} (\n  ${colDefs.join(",\n  ")}\n)` };
  }

  protected dropTable(def: DropTableQueryDef): QueryBuildResult {
    return { sql: `DROP TABLE ${this.tableName(def.table)}` };
  }

  protected renameTable(def: RenameTableQueryDef): QueryBuildResult {
    return {
      sql: `ALTER TABLE ${this.tableName(def.table)} RENAME TO ${this.expr.wrap(def.newName)}`,
    };
  }

  protected truncate(def: TruncateQueryDef): QueryBuildResult {
    // PostgreSQL: RESTART IDENTITY로 시퀀스 초기화
    return { sql: `TRUNCATE TABLE ${this.tableName(def.table)} RESTART IDENTITY` };
  }

  //#endregion

  //#region ========== DDL - Column ==========

  protected addColumn(def: AddColumnQueryDef): QueryBuildResult {
    const table = this.tableName(def.table);
    const col = def.column;

    let colSql = `${this.expr.wrap(col.name)} ${this.expr.renderDataType(col.dataType)}`;

    // nullable: true → NULL, else → NOT NULL
    if (col.nullable === true) {
      colSql += " NULL";
    } else {
      colSql += " NOT NULL";
    }

    if (col.autoIncrement) {
      colSql += " GENERATED BY DEFAULT AS IDENTITY";
    }

    if (col.default != null) {
      colSql += ` DEFAULT ${this.expr.escapeValue(col.default)}`;
    }

    return { sql: `ALTER TABLE ${table} ADD COLUMN ${colSql}` };
  }

  protected dropColumn(def: DropColumnQueryDef): QueryBuildResult {
    return {
      sql: `ALTER TABLE ${this.tableName(def.table)} DROP COLUMN ${this.expr.wrap(def.column)}`,
    };
  }

  protected modifyColumn(def: ModifyColumnQueryDef): QueryBuildResult {
    const table = this.tableName(def.table);
    const col = def.column;

    // PostgreSQL: ALTER COLUMN은 여러 ALTER 문이 필요
    const parts: string[] = [];

    // TYPE 변경
    parts.push(
      `ALTER COLUMN ${this.expr.wrap(col.name)} TYPE ${this.expr.renderDataType(col.dataType)}`,
    );

    // NULL 제약조건 변경
    if (col.nullable === false) {
      parts.push(`ALTER COLUMN ${this.expr.wrap(col.name)} SET NOT NULL`);
    } else {
      parts.push(`ALTER COLUMN ${this.expr.wrap(col.name)} DROP NOT NULL`);
    }

    // DEFAULT 변경
    if (col.default != null) {
      parts.push(
        `ALTER COLUMN ${this.expr.wrap(col.name)} SET DEFAULT ${this.expr.escapeValue(col.default)}`,
      );
    }

    return { sql: `ALTER TABLE ${table} ${parts.join(", ")}` };
  }

  protected renameColumn(def: RenameColumnQueryDef): QueryBuildResult {
    const table = this.tableName(def.table);
    return {
      sql: `ALTER TABLE ${table} RENAME COLUMN ${this.expr.wrap(def.column)} TO ${this.expr.wrap(def.newName)}`,
    };
  }

  //#endregion

  //#region ========== DDL - Constraint ==========

  protected addPrimaryKey(def: AddPrimaryKeyQueryDef): QueryBuildResult {
    const table = this.tableName(def.table);
    const cols = def.columns.map((c) => this.expr.wrap(c)).join(", ");
    const pkName = `PK_${def.table.name}`;
    return {
      sql: `ALTER TABLE ${table} ADD CONSTRAINT ${this.expr.wrap(pkName)} PRIMARY KEY (${cols})`,
    };
  }

  protected dropPrimaryKey(def: DropPrimaryKeyQueryDef): QueryBuildResult {
    const table = this.tableName(def.table);
    const pkName = `PK_${def.table.name}`;
    return { sql: `ALTER TABLE ${table} DROP CONSTRAINT ${this.expr.wrap(pkName)}` };
  }

  protected addForeignKey(def: AddForeignKeyQueryDef): QueryBuildResult {
    const table = this.tableName(def.table);
    const fk = def.foreignKey;
    const fkCols = fk.fkColumns.map((c) => this.expr.wrap(c)).join(", ");
    const targetTable = this.tableName(fk.targetTable);
    const targetCols = fk.targetPkColumns.map((c) => this.expr.wrap(c)).join(", ");

    let sql = `ALTER TABLE ${table} ADD CONSTRAINT ${this.expr.wrap(fk.name)} FOREIGN KEY (${fkCols}) REFERENCES ${targetTable} (${targetCols})`;

    // PostgreSQL: FK에 대한 별도 인덱스 생성 필요
    const idxName = `IDX_${def.table.name}_${fk.name.replace(/^FK_/, "")}`;
    sql += `;\nCREATE INDEX ${this.expr.wrap(idxName)} ON ${table} (${fkCols});`;

    return { sql };
  }

  protected dropForeignKey(def: DropForeignKeyQueryDef): QueryBuildResult {
    return {
      sql: `ALTER TABLE ${this.tableName(def.table)} DROP CONSTRAINT ${this.expr.wrap(def.foreignKey)}`,
    };
  }

  protected addIndex(def: AddIndexQueryDef): QueryBuildResult {
    const table = this.tableName(def.table);
    const idx = def.index;
    const cols = idx.columns.map((c) => `${this.expr.wrap(c.name)} ${c.orderBy}`).join(", ");
    const unique = idx.unique ? "UNIQUE " : "";
    return { sql: `CREATE ${unique}INDEX ${this.expr.wrap(idx.name)} ON ${table} (${cols})` };
  }

  protected dropIndex(def: DropIndexQueryDef): QueryBuildResult {
    // PostgreSQL: 인덱스는 스키마 수준에서 고유하므로 테이블명은 불필요하지만 스키마 지정 필요
    const schema = def.table.schema ?? "public";
    return { sql: `DROP INDEX ${this.expr.wrap(schema)}.${this.expr.wrap(def.index)}` };
  }

  //#endregion

  //#region ========== DDL - View/Procedure ==========

  protected createView(def: CreateViewQueryDef): QueryBuildResult {
    const view = this.tableName(def.view);
    const selectSql = this.select(def.queryDef).sql;
    return { sql: `CREATE OR REPLACE VIEW ${view} AS ${selectSql}` };
  }

  protected dropView(def: DropViewQueryDef): QueryBuildResult {
    return { sql: `DROP VIEW IF EXISTS ${this.tableName(def.view)}` };
  }

  protected createProc(def: CreateProcQueryDef): QueryBuildResult {
    const proc = this.tableName(def.procedure);

    // 파라미터 처리
    const paramList =
      def.params
        ?.map((p) => {
          let sql = `${this.expr.wrap(p.name)} ${this.expr.renderDataType(p.dataType)}`;
          if (p.default != null) {
            sql += ` DEFAULT ${this.expr.escapeValue(p.default)}`;
          }
          return sql;
        })
        .join(", ") ?? "";

    // 반환 타입 처리
    let returnClause = "VOID";
    if (def.returns && def.returns.length > 0) {
      const returnFields = def.returns
        .map((r) => `${this.expr.wrap(r.name)} ${this.expr.renderDataType(r.dataType)}`)
        .join(", ");
      returnClause = `TABLE(${returnFields})`;
    }

    let sql = `CREATE OR REPLACE FUNCTION ${proc}(${paramList})\n`;
    sql += `RETURNS ${returnClause} AS $$\n`;
    sql += `BEGIN\n`;
    sql += def.query;
    if (!def.query.trim().endsWith(";")) {
      sql += ";";
    }
    sql += `\nEND;\n`;
    sql += `$$ LANGUAGE plpgsql`;

    return { sql };
  }

  protected dropProc(def: DropProcQueryDef): QueryBuildResult {
    return { sql: `DROP FUNCTION IF EXISTS ${this.tableName(def.procedure)}()` };
  }

  protected execProc(def: ExecProcQueryDef): QueryBuildResult {
    const proc = this.tableName(def.procedure);
    if (def.params == null || Object.keys(def.params).length === 0) {
      return { sql: `SELECT * FROM ${proc}()` };
    }
    const params = Object.values(def.params)
      .map((p) => this.expr.render(p))
      .join(", ");
    return { sql: `SELECT * FROM ${proc}(${params})` };
  }

  /**
   * UPDATE/DELETE의 top/limit를 CTE로 변환
   *
   * PostgreSQL은 UPDATE/DELETE에 LIMIT을 지원하지 않으므로
   * ctid 기반 CTE로 변환한다.
   */
  private _buildLimitCte(
    def: { table: QueryDefObjectName; as: string; top?: number; limit?: [number, number]; where?: WhereExpr[]; joins?: SelectQueryDefJoin[] },
    table: string,
    alias: string,
  ): string {
    let sql = `WITH _limited AS (SELECT ${alias}.ctid FROM ${table} AS ${alias}`;

    if (def.joins != null && def.joins.length > 0) {
      const joinTables = def.joins.map((j) => {
        const from = this.renderFrom(j.from);
        return `${from} AS ${this.expr.wrap(j.as)}`;
      });
      sql += `, ${joinTables.join(", ")}`;

      const joinConditions = def.joins
        .filter((j) => j.where != null && j.where.length > 0)
        .map((j) => this.expr.renderWhere(j.where!));
      const whereCondition =
        def.where != null && def.where.length > 0
          ? this.expr.renderWhere(def.where)
          : null;
      const allConditions = [
        ...(whereCondition != null ? [whereCondition] : []),
        ...joinConditions,
      ];
      if (allConditions.length > 0) {
        sql += ` WHERE ${allConditions.join(" AND ")}`;
      }
    } else if (def.where != null && def.where.length > 0) {
      sql += ` WHERE ${this.expr.renderWhere(def.where)}`;
    }

    if (def.limit != null) {
      const [offset, count] = def.limit;
      sql += ` LIMIT ${count}`;
      if (offset > 0) sql += ` OFFSET ${offset}`;
    } else if (def.top != null) {
      sql += ` LIMIT ${def.top}`;
    }

    sql += `) `;
    return sql;
  }

  //#endregion

  //#region ========== Utils ==========

  protected clearSchema(def: ClearSchemaQueryDef): QueryBuildResult {
    const schemaName = def.schema ?? "public";
    // SQL 인젝션 방지: schema 이름 유효성 검사
    if (!/^[a-zA-Z_][a-zA-Z0-9_]*$/.test(schemaName)) {
      throw new Error(`잘못된 schema 이름: ${schemaName}`);
    }
    const schema = this.expr.escapeString(schemaName);
    return {
      sql: `
DO $$
DECLARE
  r RECORD;
BEGIN
  -- FK 제약조건 삭제
  FOR r IN (SELECT conname, conrelid::regclass AS tablename
            FROM pg_constraint
            WHERE contype = 'f' AND connamespace = '${schema}'::regnamespace)
  LOOP
    EXECUTE 'ALTER TABLE ' || r.tablename || ' DROP CONSTRAINT ' || quote_ident(r.conname);
  END LOOP;

  -- 테이블 삭제
  FOR r IN (SELECT tablename FROM pg_tables WHERE schemaname = '${schema}')
  LOOP
    EXECUTE 'DROP TABLE IF EXISTS ' || quote_ident(r.tablename) || ' CASCADE';
  END LOOP;

  -- 뷰 삭제
  FOR r IN (SELECT viewname FROM pg_views WHERE schemaname = '${schema}')
  LOOP
    EXECUTE 'DROP VIEW IF EXISTS ' || quote_ident(r.viewname) || ' CASCADE';
  END LOOP;

  -- 함수 삭제
  FOR r IN (SELECT proname, pg_get_function_identity_arguments(oid) AS args
            FROM pg_proc WHERE pronamespace = '${schema}'::regnamespace)
  LOOP
    EXECUTE 'DROP FUNCTION IF EXISTS ' || quote_ident(r.proname) || '(' || r.args || ') CASCADE';
  END LOOP;
END $$`,
    };
  }

  protected schemaExists(def: SchemaExistsQueryDef): QueryBuildResult {
    const schemaName = def.schema ?? "public";
    const schema = this.expr.escapeString(schemaName);
    return { sql: `SELECT nspname FROM pg_namespace WHERE nspname = '${schema}'` };
  }

  protected switchFk(def: SwitchFkQueryDef): QueryBuildResult {
    const table = this.tableName(def.table);
    if (def.enabled) {
      // PostgreSQL: 테이블의 모든 FK 트리거 활성화
      return { sql: `ALTER TABLE ${table} ENABLE TRIGGER ALL` };
    }
    // PostgreSQL: 테이블의 모든 FK 트리거 비활성화
    return { sql: `ALTER TABLE ${table} DISABLE TRIGGER ALL` };
  }

  //#endregion
}
